### ISSUE TITLE
feat: add the ability to convert `image/heic` to `image/jpeg` on the fly in order to be able to show in `<img />` tag

### ISSUE THREAD

**Issue by mesqueeb** [capawesome-team/capacitor-file-picker#77]
I believe we do `Capacitor.convertFileSrc(path)` to generate a string which we can bind to `<img />` src.

But `image/heic` won't work. : S

Maybe the file picker can convert `image/heic` to `image/jpeg` on the fly if it's cheap to do so

**Comment by robingenz** [comment]
I have added a new method `convertHeicToJpeg` (see #89) which can be used to convert a picked HEIC image to a JPEG image.
I have not done this on-the-fly on purpose, as not everyone may need this conversion and jpeg files would be generated unnecessarily. I also prefer to have a separate method instead of another method option. This way, error messages can also be handled separately and it feels cleaner.

Feedback is welcome!

**Comment by mesqueeb** [comment]
@robingenz this sounds good to me!
